platform :ios, '8.0'

target 'SXWaveAnimateLearn1' do
	pod 'AFNetworking', '~> 3.1.0'
	pod 'SDWebImage', '~> 3.7.6'
	pod 'YYModel', '~> 1.0.3'
	pod 'FMDB', '~> 2.6.2'
	pod 'SVProgressHUD', '~> 2.0.3'
	pod 'pop', '~> 1.0.9'
    pod 'SXWaveAnimate', '~> 1.3.6'
end
