//
//  PaintCodeTutorial.h
//  PaintCodeTutorial
//
//  Created by wsh on 16/7/27.
//  Copyright (c) 2016 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PaintCodeTutorial : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* stopWatchTargets;

// Colors
+ (UIColor*)color4;

// Drawing Methods
+ (void)drawStopWatch;
+ (void)drawStopWatch_Hand;

// Generated Images
+ (UIImage*)imageOfStopWatch;

@end
